# This file was generated by the {rix} R package v0.16.0 on 2025-09-19
# with following call:
# >rix(date = "2025-09-16",
#  > r_pkgs = c("rix",
#  > "tidyverse",
#  > "broom",
#  > "ggpubr",
#  > "modelsummary",
#  > "gtsummary",
#  > "gt",
#  > "estimatr",
#  > "sf",
#  > "quarto",
#  > "showtext",
#  > "here"),
#  > system_pkgs = c("quarto",
#  > "git",
#  > "gnumake"),
#  > git_pkgs = NULL,
#  > tex_pkgs = c("setspace",
#  > "lipsum",
#  > "txfonts",
#  > "csquotes",
#  > "geometry",
#  > "float",
#  > "multirow",
#  > "colortbl",
#  > "booktabs",
#  > "threeparttable",
#  > "caption",
#  > "xcolor",
#  > "fontspec",
#  > "amsfonts",
#  > "titling",
#  > "biblatex",
#  > "collection-bibtexextra",
#  > "hyperref",
#  > "placeins",
#  > "pdflscape",
#  > "framed"),
#  > ide = "rstudio",
#  >      project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = FALSE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-09-16.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      broom
      estimatr
      ggpubr
      gt
      gtsummary
      here
      modelsummary
      quarto
      rix
      sf
      showtext
      tidyverse;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsfonts
      biblatex
      booktabs
      caption
      collection-bibtexextra
      colortbl
      csquotes
      float
      fontspec
      framed
      geometry
      hyperref
      lipsum
      multirow
      pdflscape
      placeins
      setspace
      threeparttable
      titling
      txfonts
      xcolor;
  });
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      gnumake
      nix
      quarto
      R
      which
      pandoc;
  };
 
  wrapped_pkgs = pkgs.rstudioWrapper.override {
    packages = [  rpkgs  ];
  };
 
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [  rpkgs tex  system_packages  wrapped_pkgs ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
