# This file was generated by the {rix} R package v0.18.1 on 2026-04-23
# with following call:
# >rix(date = "2026-04-13",
#  > r_pkgs = c("rix",
#  > "tidyverse",
#  > "broom",
#  > "ggpubr",
#  > "modelsummary",
#  > "gtsummary",
#  > "gt",
#  > "estimatr",
#  > "sf",
#  > "data.table",
#  > "quarto",
#  > "showtext",
#  > "here"),
#  > system_pkgs = c("quarto",
#  > "git",
#  > "gnumake"),
#  > git_pkgs = NULL,
#  > tex_pkgs = c("setspace",
#  > "lipsum",
#  > "txfonts",
#  > "csquotes",
#  > "geometry",
#  > "float",
#  > "multirow",
#  > "colortbl",
#  > "booktabs",
#  > "threeparttable",
#  > "caption",
#  > "xcolor",
#  > "fontspec",
#  > "amsfonts",
#  > "titling",
#  > "biblatex",
#  > "collection-bibtexextra",
#  > "hyperref",
#  > "placeins",
#  > "pdflscape",
#  > "ninecolors",
#  >      "tabularray",
#  > "tcolorbox",
#  > "tikzfill",
#  > "pdfcol",
#  > "fontawesome5",
#  > "framed"),
#  > ide = "none",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = FALSE,
#  > r_ver = "4.5.3")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-04-13.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      broom
      data_table
      estimatr
      ggpubr
      gt
      gtsummary
      here
      modelsummary
      quarto
      rix
      sf
      showtext
      tidyverse;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsfonts
      biblatex
      booktabs
      caption
      collection-bibtexextra
      colortbl
      csquotes
      float
      fontawesome5
      fontspec
      framed
      geometry
      hyperref
      lipsum
      multirow
      ninecolors
      pdfcol
      pdflscape
      placeins
      setspace
      tabularray
      tcolorbox
      threeparttable
      tikzfill
      titling
      txfonts
      xcolor;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      gnumake
      nix
      quarto
      R
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs tex system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
