%***********************************************************
% ZEW Paper Template
% Simon Reif & Benedikt Stelter, 19 September 2024
%
% Preamble
% This tex code is use to be run together with the
% corresponding Quarto file.
%***********************************************************

% Packages
\documentclass[12pt,a4paper,oneside]{article} % Layout
\usepackage[utf8]{inputenc}
\usepackage[british]{babel}
\usepackage{graphicx,txfonts} % Even more symbols
\usepackage[T1]{fontenc}
\usepackage[onehalfspacing]{setspace}
\usepackage[strict=true, style=american]{csquotes}
\usepackage[lmargin=1.2in,rmargin=1.2in,tmargin=1.2in,bmargin=1.2in]{geometry}
\usepackage{float}
\usepackage{multirow}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{booktabs}
\usepackage{threeparttable}
\usepackage{subcaption}
\usepackage[dvipsnames]{xcolor}
\usepackage{fontspec}
\usepackage{amssymb} % Extra symbols
\usepackage{titling}
\usepackage[style=apa]{biblatex}
\usepackage[linktoc=all, colorlinks=true]{hyperref}


% Use packages from YMAL header:
\usepackage{bm}
\usepackage{setspace}
\usepackage{lipsum}

% Set text format
\setmainfont[BoldFont=LinLibertine_RB.ttf,
ItalicFont=LinLibertine_RI.ttf]{LinLibertine_R.ttf}
\definecolor{footnotecolor}{RGB}{82,125,164}

% Unnecessary but nice: change symbols for title page notes
\makeatletter
\def\@fnsymbol#1{\ensuremath{\ifcase#1\or \varheartsuit \or \bigstar \or \dagger\or \ddagger\or
\mathsection\or \mathparagraph\or \|\or **\or \dagger\dagger
\or \ddagger\ddagger \else\@ctrerr\fi}}
\makeatother

\settowidth{\thanksmarkwidth}{*}
\setlength{\thanksmargin}{-\thanksmarkwidth}


% Add Bib file from YMAL Header
\addbibresource{references.bib}

% Print references
 
\makeatletter
\@ifundefined{date}{}{\date{}}
\setcounter{page}{1}

\makeatletter
\renewcommand\@makefnmark{\hbox{\@textsuperscript{\normalfont\color{footnotecolor}\@thefnmark}}}
\renewcommand\@makefntext[1]{%
  \parindent 1em\noindent
            \hb@xt@1.8em{%
                \hss\@textsuperscript{\normalfont\@thefnmark}}#1}
\makeatother

\hypersetup{
		pdftitle={zewwwwEcon: A Template for Econ Articles with Quarto},
			pdfauthor={First Name; Second Author; Third Author; Fourth Author},
					pdfkeywords={These are the keywords},
		colorlinks=true,
	linkcolor={[RGB]{82,125,164}},
	filecolor={[RGB]{82,125,164}},
	citecolor={[RGB]{82,125,164}},
	urlcolor={[RGB]{82,125,164}},
	pdfcreator={LaTeX via pandoc}}

\begin{document}

%***********************************************************
% Title page
%***********************************************************

\setlength{\droptitle}{-8em}  % Change whitespace above title
	\title{	\rule{\linewidth}{0.5mm} \textbf{
		{\LARGE zewwwwEcon: A Template for Econ Articles with
Quarto \vspace{-15pt} }}\thanks{\noindent { }We would like to thank
\ldots.}  \rule{\linewidth}{0.5mm}  }
\date{\today}

\author{
		\textbf{First Name}\\
	\small{Affiliation A which is very long}\vspace{-1.5ex}\\
	\and	\textbf{Second Author}\thanks{ { }Corrseponding author: Adress,
Place.}\\
	\small{Affiliation B}\vspace{-1.5ex}\\
	\and	\textbf{Third Author}\\
	\small{Affiliation B}\vspace{-1.5ex}\\
	\small{Affiliation C}\vspace{-1.5ex}\\
	\and	\textbf{Fourth Author}\\
	\small{Affiliation B}\vspace{-1.5ex}\\
	\small{Affiliation C}\vspace{-1.5ex}\\
	\vspace{10pt}}

\maketitle
\thispagestyle{empty}

\begin{center}
\vspace{-25pt}	\noindent \textit{Preliminary draft - please do not
distribute}
\end{center}

\begin{abstract}
	\vspace{-15pt}	\singlespacing{
		\noindent O, never Shall sun that morrow see! Your face, my thane, is as
a book where men May read strange matters. To beguile the time, Look
like the time; bear welcome in your eye, Your hand, your tongue: look
like the innocent flower, But be the serpent under't. He that's coming
Must be provided for: and you shall put This night's great business into
my dispatch; Which shall to all our nights and days to come Give solely
sovereign sway and masterdom.

		\bigskip

	\noindent \textbf{Keywords}: These are the keywords  \newline
		\noindent	\textbf{JEL codes}: These are the JEL codes
}
\end{abstract}
\thispagestyle{empty}

%***********************************************************
% Main Text
%***********************************************************
\clearpage
\setcounter{page}{1}
\interfootnotelinepenalty=10000
\clearpage
\newpage{}

% Start the main text
\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Quarto enables you to weave together content and executable code.
\textcite{abadieSemiparametric2005} have not used this to put their
thoughts into a finished document, since Quarto did not exist back then.
To learn more about Quarto see \url{https://quarto.org}.\footnote{Here,
  we have an excellent example of a footnote.} You can easily refer to
parts of the paper such as Figure~\ref{fig-eventstudy} or
Table~\ref{tbl-regression2}.

Sometimes one might need equations. Just use LaTeX for this in the text
to show that \(2^{2} > 3\). You can also have your equation stand out
like this:

\begin{equation}
\frac{\partial S(\beta)}{\partial \beta} = -2X^\top (y - X\beta) = 0
\end{equation}

\begin{equation}
X^\top X \hat{\beta} = X^\top y
\end{equation}

\begin{equation}
\hat{\beta} = (X^\top X)^{-1} X^\top y
\end{equation}

\lipsum[2-4]
\clearpage

\hypertarget{figures}{%
\section{Figures}\label{figures}}

\begin{figure}

\caption{\label{fig-hist}Distribution of height (in cm) in random data}

{\centering 

\begin{figure}[H]

{\centering \includegraphics{example_paper_files/figure-pdf/Histogram-1.pdf}

}

\end{figure}

\hypertarget{fig-hist-1}{}
\vspace{-5pt}
\begin{minipage}{0.9\textwidth}
\scriptsize
\singlespacing
\textbf{Notes:} You can use this text to provide further information about the table. \lipsum[66]
\end{minipage}
\vspace{15pt}

}

\end{figure}

\lipsum[2-4]

\begin{figure}

\caption{\label{fig-barchart}Number of Federal States by Country}

{\centering 

\begin{figure}[H]

{\centering \includegraphics{example_paper_files/figure-pdf/Barchart-1.pdf}

}

\end{figure}

\hypertarget{fig-barchart-1}{}
\vspace{-5pt}
\begin{minipage}{0.9\textwidth}
\scriptsize
\singlespacing
\textbf{Notes:} You can use this text to provide further information about the table. \lipsum[66]
\end{minipage}
\vspace{15pt}

}

\end{figure}

\lipsum[1-2]

\begin{figure}

\caption{\label{fig-ts1}Displaying how things evolve over time}

{\centering 

\begin{figure}[H]

{\centering \includegraphics{example_paper_files/figure-pdf/tsplot1-1.pdf}

}

\end{figure}

\hypertarget{fig-ts1-1}{}
\vspace{-5pt}
\begin{minipage}{0.9\textwidth}
\scriptsize
\singlespacing
\textbf{Notes:} You can use this text to provide further information about the table. \lipsum[66]
\end{minipage}
\vspace{15pt}

}

\end{figure}

\lipsum[1-2]

\begin{figure}

\caption{\label{fig-scatterplot}Two groups have very different values}

{\centering 

\begin{figure}[H]

{\centering \includegraphics{example_paper_files/figure-pdf/scatterplot-1.pdf}

}

\end{figure}

\hypertarget{fig-scatterplot-1}{}
\vspace{-5pt}
\begin{minipage}{0.9\textwidth}
\scriptsize
\singlespacing
\textbf{Notes:} You can use this text to provide further information about the table. \lipsum[66]
\end{minipage}
\vspace{15pt}

}

\end{figure}

\lipsum[1]

\begin{figure}

\caption{\label{fig-dotplot}Visualizing distributions with few
observations}

{\centering 

\begin{figure}[H]

{\centering \includegraphics{example_paper_files/figure-pdf/dotplot-1.pdf}

}

\end{figure}

\hypertarget{fig-dotplot-1}{}
\vspace{-10pt}
\begin{minipage}{0.9\textwidth}
\scriptsize
\singlespacing
\textbf{Notes:} You can use this text to provide further information about the table. \lipsum[66]
\end{minipage}
\vspace{15pt}

}

\end{figure}

\lipsum[1-2]

\begin{figure}

\caption{\label{fig-eventstudy}Coefficients relative to treatment time}

{\centering 

\begin{figure}[H]

{\centering \includegraphics{example_paper_files/figure-pdf/eventstudy-1.pdf}

}

\end{figure}

\hypertarget{fig-eventstudy-1}{}
\vspace{-10pt}
\begin{minipage}{0.9\textwidth}
\scriptsize
\singlespacing
\textbf{Notes:} You can use this text to provide further information about the table. \lipsum[66]
\end{minipage}
\vspace{15pt}

}

\end{figure}

\hypertarget{tables}{%
\section{Tables}\label{tables}}

\lipsum[1-2]
\clearpage

\hypertarget{tab-descriptives}{}
\begin{longtable}[]{@{}lcc@{}}
\caption{Descriptive statistics by group }\tabularnewline
\toprule\noalign{}
\textbf{Characteristic} & \textbf{0}, N = 265 & \textbf{1}, N = 235 \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\textbf{Characteristic} & \textbf{0}, N = 265 & \textbf{1}, N = 235 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Survival & 0.16 (0.37) & 0.47 (0.50) \\
Age in years & 49.86 (16.75) & 50.50 (17.93) \\
Female & 0.51 (0.50) & 0.52 (0.50) \\
Severity Score & 0.39 (0.49) & 0.36 (0.48) \\
\end{longtable}

\vspace{-10pt}
\begin{minipage}{0.9\textwidth}
\scriptsize
\singlespacing
\textbf{Notes:} You can use this text to provide further information about the table. \lipsum[66]
\end{minipage}
\vspace{15pt}

\lipsum[1-2]
\clearpage

\hypertarget{tab-regression}{}
\begin{longtable}{lcccccc}
\caption{Linear Regression Models}\tabularnewline

\toprule
 & \multicolumn{2}{c}{Full Sample} & \multicolumn{2}{c}{Men} & \multicolumn{2}{c}{Women} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
  & (I) & (II) & (III) & (IV) & (V) & (VI) \\ 
\midrule\addlinespace[2.5pt]
Treatment & 0.310*** & 0.299*** & 0.337*** & 0.326*** & 0.284*** & 0.267*** \\ 
 & (0.040) & (0.038) & (0.057) & (0.053) & (0.055) & (0.054) \\ 
N & 500 & 500 & 242 & 242 & 258 & 258 \\ 
R² & 0.11 & 0.20 & 0.13 & 0.25 & 0.10 & 0.17 \\ 
\bottomrule
\end{longtable}

\vspace{-10pt}
\begin{minipage}{0.9\textwidth}
\scriptsize
\singlespacing
\textbf{Notes:} You can use this text to provide further information about the table. \lipsum[66]
\end{minipage}
\vspace{15pt}

\lipsum[1-2]

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\printbibliography[heading=none]

\clearpage

\newpage{}

\hypertarget{appendix}{%
\section*{Appendix}\label{appendix}}
\addcontentsline{toc}{section}{Appendix}

% Always keep this code if you want to use an appendix

\renewcommand{\thetable}{A.\arabic{table}}
\renewcommand{\thefigure}{A.\arabic{figure}}
\setcounter{table}{0}
\setcounter{figure}{0}

\clearpage

\begin{table}

\caption{\label{tbl-regression2}Linear Regression
Models}\begin{minipage}[t]{\linewidth}

{\centering 

\hypertarget{tbl-regression2-1}{}
\begin{longtable*}{lcccccc}
\toprule
 & \multicolumn{2}{c}{Full Sample} & \multicolumn{2}{c}{Men} & \multicolumn{2}{c}{Women} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
  & (I) & (II) & (III) & (IV) & (V) & (VI) \\ 
\midrule\addlinespace[2.5pt]
Treatment & 0.310*** & 0.299*** & 0.337*** & 0.326*** & 0.284*** & 0.267*** \\ 
 & (0.040) & (0.038) & (0.057) & (0.053) & (0.055) & (0.054) \\ 
N & 500 & 500 & 242 & 242 & 258 & 258 \\ 
R² & 0.11 & 0.20 & 0.13 & 0.25 & 0.10 & 0.17 \\ 
\bottomrule
\end{longtable*}

}

\end{minipage}%
\newline
\begin{minipage}[t]{\linewidth}
\subcaption{\label{tbl-regression2-2}}

{\centering 

\vspace{-10pt}
\begin{minipage}{0.9\textwidth}
\scriptsize
\singlespacing
\textbf{Notes:} You can use this text to provide further information about the table. \lipsum[66]
\end{minipage}
\vspace{15pt}

}

\end{minipage}%

\end{table}
\end{document}
